# Generated by Django 4.1.4 on 2022-12-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardar_IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
            ],
        ),
    ]
